build:
  image: docker:latest
  stage: Build
  variables:
  IMAGE: ${CI_REGISTRY_USER}/devops:2.0.0
    script:
      - "docker build -t ${CI_REGISTRY_USER}/devops:2.0.0 ."
      - "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}"
      - "docker push ${CI_REGISTRY_USER}/devops:2.0.0"


deploy:
  image: ubuntu:latest
  stage: Deploy
  script:
      - docker pull ${CI_REGISTRY_USER}/devops:2.0.0"
      - docker run --rm -d --name meuapp -p $APP_PORT:$APP_PORT ${CI_REGISTRY_USER}/devops:2.0.0"